### ISSUE TITLE
请赐教

### ISSUE THREAD

**Issue by heweizhe** [yagay/android_device_nubia_nx507j#1]
nx507j cm13已编译成功，感谢您的相关源码。请问device,kernel, vendor是如何修改（或从何处获取）的呢？望指点。

**Comment by yagay** [comment]
都是用的505 意大利P大的源码修改的

**Comment by heweizhe** [comment]
我看到P大的代码还只是适配cm-12.1的，您能简单介绍下修改思路吗？或者是否有推荐的blog或者文档来学习呢？

**Comment by yagay** [comment]
p大的有cm13啊，小牛所有的cm13基本上都是参考p大的源码来的

**Comment by heweizhe** [comment]
好的，我再研究下，感谢~
